apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: andresvidal/rpi3-mongodb3
          ports:
            - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-service
  template:
    metadata:
      labels:
        app: mongo-service
    spec:
      containers:
        - name: mongo-service
          image: juierror/todolist-microservice_mongo-service
          ports:
            - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-service
  labels:
    app: todolist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-service
  template:
    metadata:
      labels:
        app: todolist-service
    spec:
      containers:
        - name: todolist-service
          image: juierror/todolist-microservice_todolist-service
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: juierror/todolist-microservice_user-service
          ports:
            - containerPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-service
  labels:
    app: management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-service
  template:
    metadata:
      labels:
        app: management-service
    spec:
      containers:
        - name: management-service
          image: juierror/todolist-microservice_management-service
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  type: ClusterIP
  selector:
    app: todolist-service
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - name: http
    port: 3002
    targetPort: 3002
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongo-service
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  type: ClusterIP
  selector:
    app: management-service
  ports:
  - name: http
    port: 3003
    targetPort: 3003
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - name: http
    port: 27017
    targetPort: 27017
